# Generated by Django 6.0.6 on 2026-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(),
        ),
    ]
